<?php
/**
 * TP-HR — Locked native component class registry (PHP).
 * Maps logical component names → CSS classes (native-shell.css + header inline legacy).
 *
 * Usage: $C = require __DIR__ . '/component_registry.php'; echo $C['NativeCard'];
 *
 * @return array<string, string>
 */
return [
    'AppShell' => 'tp-native-app tp-app-shell',
    'SafeAreaHeader' => 'mobile-app-header header-glass tp-safe-area-header',
    'PageHeader' => 'tp-native-section-title section-title',
    'BottomTabNavigation' => 'tp-native-bottom-tab-nav app-shell-mobile-only',
    'StickyPrimaryAction' => 'home-sticky-cta tp-sticky-primary-action',
    'NativeCard' => 'native-card tp-native-card',
    'NativeSummaryCard' => 'stat-card tp-native-summary-card',
    'NativeDataCard' => 'glass-card tp-native-data-card',
    'NativeListItem' => 'tp-native-list-item tp-native-list-row',
    'NativeFormGroup' => 'tp-native-form-group',
    'NativeInput' => 'input-field tp-native-input',
    'NativeSelect' => 'input-field tp-native-select',
    'NativeTextarea' => 'input-field tp-native-textarea',
    'NativeButtonPrimary' => 'btn-primary tp-native-btn-primary',
    'NativeButtonSecondary' => 'btn-secondary tp-native-btn-secondary',
    'NativeIconButton' => 'tp-native-icon-btn',
    'NativeStatusBadge' => 'badge',
    'NativeSectionTitle' => 'section-title tp-native-section-title',
    'NativeFilterBar' => 'tp-native-filter-bar',
    'NativeSearchBar' => 'tp-native-search-bar',
    'NativeDatePickerTrigger' => 'input-date-shell',
    'NativeModal' => 'tp-native-modal fixed inset-0',
    'NativeBottomSheet' => 'tp-native-bottom-sheet',
    'NativeToast' => 'toast-panel',
    'NativeLoadingState' => 'tp-native-loading-state',
    'NativeEmptyState' => 'tp-native-empty-state',
    'NativeErrorState' => 'tp-native-error-state',
    'NativeSuccessState' => 'tp-native-success-state',
    'NativeConfirmationDialog' => 'tp-native-confirmation-dialog',
    'NativeTableToCardPattern' => 'tp-native-table-shell',
    'NativeProgressStep' => 'tp-native-progress-step',
    'NativeActionSheet' => 'tp-native-action-sheet',
    'NativeQuickActionCard' => 'quick-action tp-native-quick-action-card',
    'NativeInfoBlock' => 'tp-native-info-block',
    'NativeWarningBlock' => 'tp-native-warning-block',

    /* --------- iOS26 logical names → same classes (explicit lock map aliases) --------- */
    'IOSAppShell' => 'tp-native-app tp-app-shell',
    'IOSSafeAreaHeader' => 'mobile-app-header header-glass tp-safe-area-header',
    'IOSLargeTitleHeader' => 'tp-native-section-title section-title',
    'IOSCompactHeader' => 'mobile-app-header header-glass',
    'IOSLiquidTabBar' => 'tp-native-bottom-tab-nav app-shell-mobile-only',
    'IOSFloatingActionBar' => 'tp-native-action-sheet',
    'IOSStickyPrimaryCTA' => 'home-sticky-cta tp-sticky-primary-action',
    'IOSGlassControl' => 'glass-card tp-native-data-card',
    'IOSGlassButton' => 'btn-secondary tp-native-btn-secondary',
    'IOSPrimaryButton' => 'btn-primary tp-native-btn-primary',
    'IOSSecondaryButton' => 'btn-secondary tp-native-btn-secondary',
    'IOSDestructiveButton' => 'mobile-menu-logout-btn',
    'IOSIconButton' => 'tp-native-icon-btn',
    'IOSCard' => 'native-card tp-native-card',
    'IOSInsetGroupedCard' => 'native-card tp-native-card tp-native-well',
    'IOSSummaryCard' => 'stat-card tp-native-summary-card',
    'IOSDataCard' => 'glass-card tp-native-data-card',
    'IOSListItem' => 'tp-native-list-item tp-native-list-row',
    'IOSInsetListGroup' => 'tp-native-stack-cards',
    'IOSFormGroup' => 'tp-native-form-group',
    'IOSInput' => 'input-field tp-native-input',
    'IOSSelect' => 'input-field tp-native-select',
    'IOSTextarea' => 'input-field tp-native-textarea',
    'IOSDatePickerTrigger' => 'input-date-shell',
    'IOSSegmentedControl' => 'tp-native-filter-bar',
    'IOSSearchBar' => 'tp-native-search-bar',
    'IOSFilterSheet' => 'tp-native-bottom-sheet',
    'IOSModal' => 'tp-native-modal fixed inset-0',
    'IOSBottomSheet' => 'tp-native-bottom-sheet',
    'IOSToast' => 'toast-panel',
    'IOSLoadingState' => 'tp-native-loading-state',
    'IOSSkeletonState' => 'tp-native-app-loading',
    'IOSEmptyState' => 'tp-native-empty-state',
    'IOSErrorState' => 'tp-native-error-state',
    'IOSSuccessState' => 'tp-native-success-state',
    'IOSConfirmationDialog' => 'tp-native-confirmation-dialog',
    'IOSStatusBadge' => 'badge',
    'IOSInfoBlock' => 'tp-native-info-block',
    'IOSWarningBlock' => 'tp-native-warning-block',
    'IOSTableToCardPattern' => 'tp-native-table-shell',
    'IOSProgressStep' => 'tp-native-progress-step',
    'IOSMasterScreen' => 'tp-ios-master-screen',

    'IOSStickyCTAGlass' => 'tp-ios-sticky-cta-slab',
    'IOSAttendanceWell' => 'tp-ios-attendance-panel',
    'IOSScrollContainer' => 'tp-native-stack--page',
    'IOSKeyboardSafeForm' => 'tp-native-form-group',
];
