CREATE TABLE IF NOT EXISTS hr_attendance_outside_requests (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id INT NOT NULL,
    attendance_id BIGINT NULL,
    request_type ENUM('CHECK_IN','CHECK_OUT') NOT NULL,
    request_date DATE NOT NULL,
    request_time DATETIME NOT NULL,
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    photo_path VARCHAR(255),
    reason TEXT NOT NULL,
    status ENUM('PENDING','APPROVED','REJECTED','CANCELLED') DEFAULT 'PENDING',
    reviewed_by INT,
    reviewed_at DATETIME,
    review_remarks TEXT,
    request_ip VARCHAR(45),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (attendance_id) REFERENCES hr_attendances(id),
    FOREIGN KEY (reviewed_by) REFERENCES users(id),
    INDEX idx_status (status),
    INDEX idx_user_type_date (user_id, request_type, request_date),
    INDEX idx_attendance_id (attendance_id),
    INDEX idx_request_time (request_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
